### ISSUE TITLE
Longer strings are not supported

### ISSUE THREAD

**Issue by praus** [scrthq/PEMEncrypt#3]
Hi! I just wanted to drop a friendly note that your library won't be able to encrypt strings longer than the key modulus size in bytes minus padding size (11 bytes for PKCS #1). For example, if your RSA key is 2048 bit long (therefore its modulus is 2048 bits/256 bytes), you will only be able to encrypt plaintexts that are 245 bytes in length or less. RSACryptoServiceProvider will throw CryptographicException when the plaintext is too long. You might want to point this out in the documentation.

Useful links:
- https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider.encrypt?view=netframework-4.8#System_Security_Cryptography_RSACryptoServiceProvider_Encrypt_System_Byte___System_Boolean_
- https://tools.ietf.org/html/rfc8017#section-7.2.1

**Comment by scrthq** [comment]
Thanks for the pointer, @praus !!! I'll add it to the documentation!

**Comment by scrthq** [comment]
Added here! Thanks again!

https://github.com/scrthq/PEMEncrypt#im-receiving-an-error-message-that-says-bad-length-whats-happening
