### ISSUE TITLE
Create Destination Folder

### ISSUE THREAD

**Issue by Rick-2CA** [scrthq/PEMEncrypt#5]
Throwing out consideration for the creation of the destination folder when a path is given with `New-RSAKeyPair`.  Especially when choosing the default path where on Windows creating a folder that begins with a dot is not user friendly in the GUI.

**Comment by scrthq** [comment]
I can dig it! Just to confirm, you're talking about creating the path leading up to the desired keyfile name if it does not already exist, right? e.g. default Windows doesn't include the `.ssh` folder in the user profile?

**Comment by scrthq** [comment]
Adding this into v0.2.1, deploying momentarily! Updated the verbosity a little bit on `New-RSAKeyPair` as well:

![image](https://user-images.githubusercontent.com/12724445/63640912-721fd580-c66b-11e9-83f4-9a9b37648c41.png)
